### PR TITLE
Fix Registry install on windows

### PR DESCRIPTION
**Pull request by RyanJField**
Fixes issue with Windows 10 trying to load the store python.

### CODE REVIEW

**Comment by bobturneruk** [comment]
Tag me for review whenever.

**Comment by RyanJField** [comment]
@bobturneruk This should fix the windows issue, can you test with the app executable aliases on please.

The tests are failing because GRID moved to ror and will be fixed with a merge of the feature/address_on_local branch.

**Comment by bobturneruk** [comment]
Will do, but may not be today.

**Comment by RyanJField** [comment]
> Will do, but may not be today.

No rush

**Comment by RyanJField** [comment]
> I can use this branch to install on Windows 10, Python 10 (Anaconda).
> 
> It seems some of the CI is currently failing on Ubuntu - not sure why.
> 
> Perhaps moving (some of) the CI onto an OS matrix including Windows would now be possible.

The failing (CI) tests should be fixed by #256, the GRID API is now defunct and needed to be moved to ROR.

**Pull request merged**
