### PR TITLE
Fix new bugs

### LINKED ISSUE #68: `fair pull` is registering external DataProducts as `file_type` `py`

### LINKED ISSUE #69: Register a Namespace entry in `fair init`
Include `full_name` and `website` as your ORCID iD

### LINKED ISSUE #70: `remote_repo` is missing from the working config

### LINKED ISSUE #71: `run_metadata: write_data_store:` value needs to end in a slash

### PR DESCRIPTION
**Pull request by richardreeve**
- fixes #68 and registers file types correctly
- fixes #69 and registers user namespace automatically in `fair init`
- fixes #70 and adds `remote_repo:` to `run_metadata:`
- fixes #71 and adds a path separator to folder names

@soniamitchell - can you check this works please?

### CODE REVIEW

**Comment by soniamitchell** [comment]
Testing:
- [ ] fair pull is registering external DataProducts as `file_type` py and registers file types correctly
- [ ] Register a Namespace entry in `fair init` and registers user namespace automatically in `fair init`
- [ ] `remote_repo` is missing from the working config and adds `remote_repo:` to `run_metadata:`
- [ ] `run_metadata: write_data_store:` value needs to end in a slash and adds a path separator to folder names

**Comment by soniamitchell** [comment]
* when `write_data_store` is included in the user-written config, `fair run` doesn't check whether it ends in a slash
* `fair init --using sonia.yaml` no longer works correctly (and so checking the Namespace entry is incomplete) - `fair` is unable to find the registry:
```
Initialised empty fair repository in /Users/Soniam/Desktop/git/FAIRDataPipeline/rSimpleModel/.fair
Error: Failed to find local registry executable      
'/Users/runner/work/SimpleModel/SimpleModel/.fair/registry/scripts/start_fair_registry', is the FAIR data pipeline properly    installed on this system?  
```
* when running through `fair init`, curser keys are inoperable
* after `fair init` is complete:
```
Initialised empty fair repository in /Users/Soniam/Desktop/git/FAIRDataPipeline/rSimpleModel/.fair
Traceback (most recent call last):
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/bin/fair", line 5, in <module>
    cli()
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/cli.py", line 120, in init
    export_as=export
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/session.py", line 605, in initialise
    _uri
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/registry/storage.py", line 349, in store_namespace
    uri, "namespace", data=_data, params={"name": namespace_label}
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/registry/requests.py", line 407, in post_else_get
    token = local_token()
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/registry/requests.py", line 65, in local_token
    _local_token_file = os.path.join(fdp_com.registry_home(), "token")
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/common.py", line 53, in registry_home
    _glob_conf = yaml.safe_load(open(global_fdpconfig()))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Soniam/.fair/cli/cli-config.yaml'
```

**Comment by richardreeve** [comment]
> * when `write_data_store` is included in the user-written config, `fair run` doesn't check whether it ends in a slash
@soniamitchell - hopefully this is fixed now.

**Comment by richardreeve** [comment]
> * `fair init --using sonia.yaml` no longer works correctly (and so checking the Namespace entry is incomplete) - `fair` is unable to find the registry:
> 
> ```
> Initialised empty fair repository in /Users/Soniam/Desktop/git/FAIRDataPipeline/rSimpleModel/.fair
> Error: Failed to find local registry executable      
> '/Users/runner/work/SimpleModel/SimpleModel/.fair/registry/scripts/start_fair_registry', is the FAIR data pipeline properly    installed on this system?  
> ```
If that problem is mine, could you give me your `sonia.yaml` via Zulip, because I can't reproduce it... thanks! Also:
> * when running through `fair init`, curser keys / tab complete are inoperable - I'd like to be able to paste and edit
This isn't fixable (at least by me!), sorry...

**Comment by soniamitchell** [comment]
Turns out it works fine 👍 it was a problem with `local: data_store:` and `local: directory:`, perhaps a check could be made as to whether `local: directory:` is accurate prior to initialising the empty fair repository?

**Comment by richardreeve** [comment]
> Turns out it works fine 👍 it was a problem with `local: data_store:` and `local: directory:`, perhaps a check could be made as to whether `local: directory:` is accurate prior to initialising the empty fair repository?

Great. Maybe add a new issue for this because I can't fix it now though...

**Comment by richardreeve** [comment]
@soniamitchell - okay, maybe(?!) fixed now. This may also accidentally fix #74 btw.

**Comment by richardreeve** [comment]
Nope - maybe not. Fixed a few problems, but created a new one...

**Comment by richardreeve** [comment]
Okay - trying this again @soniamitchell - I think it really is fixed now. This may also accidentally fix #74 btw. It gives inscrutable errors when you do things in the wrong order sadly, but otherwise I hope good?

**Pull request merged**
